name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # 触发条件：推送版本标签，如 v1.0.0
  workflow_dispatch:  # 允许手动触发

env:
  FLUTTER_VERSION: '3.32.0'  # 指定Flutter版本
  JAVA_VERSION: '17'

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
      
    - name: Create keystore from secrets
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/upload-keystore.jks
        chmod 600 android/upload-keystore.jks

    - name: Create key.properties
      run: |
        cat > android/key.properties << EOF
        storeFile=../upload-keystore.jks
        storePassword=${{ secrets.KEYSTORE_PASSWORD }}
        keyAlias=${{ secrets.KEY_ALIAS }}
        keyPassword=${{ secrets.KEY_PASSWORD }}
        EOF
        chmod 600 android/key.properties

    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Build Android APK
      run: flutter build apk --release

    - name: Get version from pubspec.yaml
      id: version
      run: |
        VERSION=$(grep '^version:' pubspec.yaml | cut -d ' ' -f 2 | cut -d '+' -f 1)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Detected version: $VERSION"

    - name: List APK files (debug)
      run: |
        echo "Listing build directory structure:"
        find build -name "*.apk" -type f 2>/dev/null || echo "No APK files found"
        ls -la build/app/outputs/flutter-apk/ || echo "Flutter APK directory not found"

    - name: Rename APK
      run: |
        if [ -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
          mv build/app/outputs/flutter-apk/app-release.apk \
             build/app/outputs/flutter-apk/invest-ledger-v${{ steps.version.outputs.version }}-android.apk
          echo "APK renamed successfully"
        else
          echo "Error: APK file not found at expected location"
          exit 1
        fi

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/invest-ledger-v${{ steps.version.outputs.version }}-android.apk
        
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Build Windows
      run: flutter build windows --release
      
    - name: Get version from pubspec.yaml
      id: version
      shell: powershell
      run: |
        $version = (Select-String -Path "pubspec.yaml" -Pattern "^version:" | ForEach-Object { $_.Line.Split(' ')[1].Split('+')[0] })
        echo "version=$version" >> $env:GITHUB_OUTPUT
        
    - name: List Windows build files (debug)
      shell: powershell
      run: |
        Write-Host "Listing Windows build directory:"
        if (Test-Path "build\windows\x64\runner\Release") {
          Get-ChildItem -Path "build\windows\x64\runner\Release" -Recurse
        } else {
          Write-Host "Release directory not found"
        }

    - name: Create Windows archive
      shell: powershell
      run: |
        if (Test-Path "build\windows\x64\runner\Release") {
          Compress-Archive -Path "build\windows\x64\runner\Release\*" -DestinationPath "invest-ledger-v${{ steps.version.outputs.version }}-windows.zip"
          Write-Host "Windows archive created successfully"
        } else {
          Write-Host "Error: Windows build directory not found"
          exit 1
        }
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-app
        path: invest-ledger-v${{ steps.version.outputs.version }}-windows.zip

  create-release:
    name: Create GitHub Release
    needs: [build-android, build-windows]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get version from pubspec.yaml
      id: version
      run: |
        VERSION=$(grep '^version:' pubspec.yaml | cut -d ' ' -f 2 | cut -d '+' -f 1)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Download Android artifact
      uses: actions/download-artifact@v3
      with:
        name: android-apk
        path: ./artifacts/

    - name: Download Windows artifact
      uses: actions/download-artifact@v3
      with:
        name: windows-app
        path: ./artifacts/
        
    - name: Generate changelog
      id: changelog
      run: |
        if [ -f "CHANGELOG.md" ]; then
          # 提取最新版本的更新日志
          CHANGELOG=$(awk '/^## \[?[0-9]/{if(p) exit; p=1; next} p' CHANGELOG.md | head -20)
          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="Release v${{ steps.version.outputs.version }}"
          fi
        else
          CHANGELOG="Release v${{ steps.version.outputs.version }}"
        fi
        {
          echo "changelog<<EOF"
          echo "$CHANGELOG"
          echo "EOF"
        } >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: Release v${{ steps.version.outputs.version }}
        body: |
          ## 🚀 投资账本 v${{ steps.version.outputs.version }}
          
          ### 📱 下载
          - **Android APK**: 适用于Android设备
          - **Windows**: 适用于Windows 10/11
          
          ### 📋 更新内容
          ${{ steps.changelog.outputs.changelog }}
          
          ### 🔧 安装说明
          
          **Android:**
          1. 下载 APK 文件
          2. 在设备上启用"未知来源"安装
          3. 安装 APK 文件
          
          **Windows:**
          1. 下载 ZIP 文件
          2. 解压到任意目录
          3. 运行 `invest_ledger.exe`
          
          ---
          
          构建时间: ${{ github.event.head_commit.timestamp }}
          提交: ${{ github.sha }}
        files: |
          ./artifacts/invest-ledger-v${{ steps.version.outputs.version }}-android.apk
          ./artifacts/invest-ledger-v${{ steps.version.outputs.version }}-windows.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
